### ISSUE TITLE
.NET 8 migration meta issue

### ISSUE THREAD

**Issue by PathogenDavid** [bonsai-rx/bonsai#1953]
While doing https://github.com/bonsai-rx/bonsai/pull/1952 I did an audit of all the other projects to get an idea of non-core .NET modernization work that remains.

I also tried to check at a glance what might be holding back specific projects (if anything.)

@glopesdev feel free to edit these lists if you see anything missing off the top of your head.

## `bonsai-rx/bonsai` Projects

* [ ] `Bonsai.Audio`
  * `openal.redist` is erroneously marked as framework-specific
  * Need to update `OpenTK`
* [ ] `Bonsai.Design.Visualizers`
  * `ZedGraph`
* [ ] `Bonsai.Dsp`
  * [ ] `Bonsai.Dsp.Design`
* [ ] `Bonsai.Osc`
* [ ] `Bonsai.Scripting.Expressions`
  * Depends on `System.Linq.Dynamic` which was replaced by `System.Linq.Dynamic.Core`
  * [ ] `Bonsai.Scripting.Expressions.Design`
* [ ] `Bonsai.Shaders`
  * Need to update `OpenTK`
  * [ ] `Bonsai.Shaders.Design`
  * [ ] `Bonsai.Shaders.Rendering`
* [ ] `Bonsai.System.Design`
* [ ] `Bonsai.Vision`
  * [ ] `Bonsai.Vision.Design`
* [ ] `Bonsai.Windows.Input`

## Other `bonsai-rx` repos

TBD

## Important community packages

TBD

## Misc tasks

* [ ] Figure out if there's a way for Bonsai on .NET 8 to run on Mono
  * My understanding is that Mono works with modern .NET, but the old Mono BCL does not (which means the Mono version of `System.Windows.Forms` does not)
  * This in-development project might be helpful: https://github.com/DanielVanNoord/System.Windows.Forms
  * Maybe the answer is that we need to multi-target for the sake of Mono users until he UI migration happens
* [ ] Update `ProjectTemplate` - This needs modernizing in general, but it might be good to at least modify it for multi-targeting (if we want to impose multi-targeting on extension developers during the transition)
  * [ ] Semi-related: https://github.com/bonsai-rx/bonsai/issues/1897
